In [2]:
import pandas as pd

In [5]:
cd cityreader

/Users/huskeycl/Documents - LSDS Lambda School/LSDS-Computer-Science-CS/Sprint-Challenge--Intro-Python/src/cityreader

In [6]:
pwd

'/Users/huskeycl/Documents - LSDS Lambda School/LSDS-Computer-Science-CS/Sprint-Challenge--Intro-Python/src/cityreader'

In [7]:
cities_df = pd.read_csv("cities.csv")
cities_df

,city,state_name,county_name,lat,lng,population,density,timezone,zips
0,Seattle,Washington,King,47.6217,-122.3238,3541236,3243,America/Los_Angeles,98109 98108 98104 98107 98106 98101 98103 9810...
1,Richmond,Virginia,Richmond (city),37.5294,-77.4755,1041877,1440,America/New_York,23219 23222 23223 23220 23221 23226 23227 2322...
2,Virginia Beach,Virginia,Virginia Beach (city),36.7335,-76.0435,1487505,699,America/New_York,23459 23451 23453 23452 23455 23457 23456 2345...
3,Washington,District of Columbia,District of Columbia,38.9047,-77.0163,5191844,4301,America/New_York,20010 20011 20012 20015 20228 20520 20307 2041...
4,Milwaukee,Wisconsin,Milwaukee,43.0640,-87.9669,1377104,2388,America/Chicago,53203 53202 53207 53206 53205 53204 53209 5320...
5,Orlando,Florida,Orange,28.4801,-81.3448,1757288,1041,America/New_York,32829 32827 32824 32822 32804 32805 32806 3280...
6,Miami,Florida,Miami-Dade,25.7840,-80.2102,6247425,4866,America/New_York,33129 33125 33126 33127 33128 33149 33144 3314...
7,Tampa,Florida,Hillsborough,27.9937,-82.4454,2744107,1283,America/New_York,33637 33629 33621 33620 33647 33602 33619 3361...
8,Jacksonville,Florida,Duval,30.3322,-81.6749,1141459,454,America/New_York,32224 32225 32226 32227 32220 32221 32222 3222...
9,Albuquerque,New Mexico,Bernalillo,35.1055,-106.6476,759517,1147,America/Denver,87121 87123 87112 87113 87110 87111 87116 8711...
10,Fort Worth,Texas,Tarrant,32.7813,-97.3466,854113,968,America/Chicago,76164 76040 76134 76135 76137 76131 76132 7613...
11,McAllen,Texas,Hidalgo,26.2203,-98.2457,798187,1113,America/Chicago,78504 78503 78501 78502 78505
12,El Paso,Texas,El Paso,31.8478,-106.4310,845059,1027,America/Denver,79901 79902 79903 79904 79905 79906 79907 7993...
13,Dallas,Texas,Dallas,32.7938,-96.7659,5634307,1490,America/Chicago,75287 75098 75233 75231 75234 75254 75251 7525...
14,Austin,Texas,Travis,30.3038,-97.7545,1633847,1170,America/Chicago,78749 78748 78741 78742 78745 78744 78747 7874...
15,Houston,Texas,Harris,29.7871,-95.3936,5424720,1412,America/Chicago,77069 77068 77061 77060 77063 77062 77065 7706...
16,San Antonio,Texas,Bexar,29.4722,-98.5247,1976787,1250,America/Chicago,78112 78233 78259 78258 78252 78251 78250 7825...
17,New Orleans,Louisiana,Orleans,30.0687,-89.9288,1024421,892,America/Chicago,70139 70130 70131 70114 70115 70116 70117 7011...
18,Charlotte,North Carolina,Mecklenburg,35.2080,-80.8308,1438351,1065,America/New_York,28269 28262 28105 28280 28282 28209 28208 2820...
19,Raleigh,North Carolina,Wake,35.8323,-78.6441,1005457,1225,America/New_York,27617 27616 27615 27614 27613 27612 27610 2760...
20,Omaha,Nebraska,Douglas,41.2634,-96.0453,792463,1295,America/Chicago,68116 68118 68106 68107 68105 68108 68178 6811...
21,Memphis,Tennessee,Shelby,35.1047,-89.9773,1069661,794,America/Chicago,38122 38125 38127 38107 38106 38105 38104 3810...
22,Nashville,Tennessee,Davidson,36.1714,-86.7844,1065078,535,America/Chicago,37027 37138 37076 37072 37201 37203 37206 3724...
23,Buffalo,New York,Erie,42.9016,-78.8487,920136,2456,America/New_York,14208 14209 14202 14203 14201 14206 14207 1420...
24,Queens,New York,Queens,40.7498,-73.7976,2333054,8247,America/New_York,11361 11362 11363 11364 11354 11355 11356 1135...
25,New York,New York,New York,40.6943,-73.9249,19164071,10934,America/New_York,11229 11226 11225 11224 11222 11221 11220 1138...
26,Bronx,New York,Bronx,40.8501,-73.8662,1455720,13202,America/New_York,10453 10457 10460 10458 10467 10468 10451 1045...
27,Brooklyn,New York,Kings,40.6501,-73.9496,2629150,14606,America/New_York,11212 11213 11216 11233 11238 11209 11214 1122...
28,Manhattan,New York,New York,40.7834,-73.9662,1643734,27799,America/New_York,10026 10027 10030 10037 10039 10001 10011 1001...
29,Philadelphia,Pennsylvania,Philadelphia,40.0076,-75.1340,5591554,4511,America/New_York,19154 19151 19150 19153 19152 19102 19103 1910...
30,Pittsburgh,Pennsylvania,Allegheny,40.4396,-79.9763,1722206,2116,America/New_York,15216 15217 15214 15212 15210 15211 15218 1521...
31,Sacramento,California,Sacramento,38.5666,-121.4683,1830061,1952,America/Los_Angeles,95821 95823 95838 95832 95833 95831 95834 9583...
32,Riverside,California,Riverside,33.9382,-117.3949,2065627,1544,America/Los_Angeles,92508 92503 92501 92505 92504 92507 92506 9250...
33,San Francisco,California,San Francisco,37.7561,-122.4429,3548847,7170,America/Los_Angeles,94130 94131 94132 94133 94134 94108 94103 9410...
34,San Diego,California,San Diego,32.8312,-117.1225,3181172,1670,America/Los_Angeles,92109 92108 92106 92103 92111 92117 92154 9214...
35,San Jose,California,Santa Clara,37.3020,-121.8488,1804359,2242,America/Los_Angeles,95118 95128 95124 95125 95126 95127 95120 9512...
36,Los Angeles,California,Los Angeles,34.1140,-118.4068,12740381,3275,America/Los_Angeles,90291 90293 90292 90029 91316 91311 90035 9000...
37,Las Vegas,Nevada,Clark,36.2288,-115.2603,2044731,1829,America/Los_Angeles,89149 89107 89106 89104 89102 89101 89108 8913...
38,Denver,Colorado,Denver,39.7621,-104.8759,2741534,1745,America/Denver,80264 80218 80230 80231 80236 80237 80235 8023...
39,Chicago,Illinois,Cook,41.8373,-87.6861,8639278,4585,America/Chicago,60018 60649 60641 60640 60643 60642 60645 6064...
40,Atlanta,Georgia,Fulton,33.7627,-84.4231,5080712,1370,America/New_York,30334 30331 30332 30309 30308 30307 30303 3035...
41,Indianapolis,Indiana,Marion,39.7771,-86.1458,1550488,913,America/Indiana/Indianapolis,46237 46218 46219 46217 46214 46260 46268 4622...
42,Oklahoma City,Oklahoma,Oklahoma,35.4677,-97.5138,948154,406,America/Chicago,73012 73099 73097 73119 73118 73114 73117 7311...
43,Phoenix,Arizona,Maricopa,33.5722,-112.0891,4054083,1204,America/Phoenix,85008 85009 85003 85006 85007 85004 85083 8508...
44,Tucson,Arizona,Pima,32.1558,-110.8777,860333,887,America/Phoenix,85705 85707 85706 85756 85723 85726 85724 8570...
45,Bridgeport,Connecticut,Fairfield,41.1909,-73.1958,934289,3508,America/New_York,06605 06604 06607 06606 06608 06610 06601 0660...
46,Hartford,Connecticut,Hartford,41.7661,-72.6834,913587,2737,America/New_York,06106 06105 06103 06120 06112 06160 06114 0610...
47,Baltimore,Maryland,Baltimore (city),39.3051,-76.6144,2181206,2931,America/New_York,21218 21211 21210 21213 21212 21215 21214 2121...
48,Boston,Massachusetts,Suffolk,42.3189,-71.0838,4556916,5373,America/New_York,02120 02121 02122 02124 02125 02126 02127 0212...
49,Cleveland,Ohio,Cuyahoga,41.4766,-81.6805,1731637,1917,America/New_York,44135 44128 44120 44119 44113 44112 44111 4411...
50,Columbus,Ohio,Franklin,39.9859,-82.9852,1495146,1522,America/New_York,43026 43109 43054 43220 43221 43222 43223 4322...
51,Cincinnati,Ohio,Hamilton,39.1412,-84.5060,1634573,1480,America/New_York,45219 45213 45212 45211 45217 45216 45214 4522...
52,Salt Lake City,Utah,Salt Lake,40.7774,-111.9301,1061156,672,America/Denver,84116 84115 84113 84112 84111 84144 84128 8418...
53,Saint Louis,Missouri,St. Louis (city),38.6358,-90.2451,2096990,1940,America/Chicago,63110 63111 63112 63113 63115 63116 63118 6312...
54,Kansas City,Missouri,Jackson,39.1239,-94.5541,1590762,590,America/Chicago,64163 64164 64165 64167 64161 64053 64119 6411...
55,Minneapolis,Minnesota,Hennepin,44.9635,-93.2679,2866604,2957,America/Chicago,55402 55409 55408 55407 55406 55405 55404 5540...
56,Detroit,Michigan,Wayne,42.3834,-83.1024,3520589,1872,America/Detroit,48209 48208 48201 48207 48206 48205 48204 4820...
57,Providence,Rhode Island,Providence,41.8229,-71.4186,1198789,3760,America/New_York,02903 02906 02907 02904 02905 02908 02909 0291...
58,Louisville,Kentucky,Jefferson,38.1662,-85.6488,1003412,902,America/New_York,40177 40245 40241 40218 40219 40214 40216 4021...
59,Portland,Oregon,Multnomah,45.5372,-122.6500,2027629,1851,America/Los_Angeles,97227 97221 97220 97229 97203 97202 97201 9720...

In [8]:
cities_df.shape

(60, 9)